### ISSUE TITLE
COleScript::Compile hook not working

### ISSUE THREAD

**Issue by baxitaurus** [cuckoosandbox/monitor#75]
Hi guys, first of all thanks alot for your excellent work.

I'm having issues in getting the `COleScript::Compile` hook defined in `insn/vbscript.yml` to work properly, and that's confirmed by the `DEBUG:Error resolving function vbscript!COleScript_Compile through our custom callback` log messages I see in the  `analysis.log` file.

I followed the steps described in [this](https://hatching.io/blog/vbscript-hooking) article to set up my hook, since my `C:\Windows\System32\vbscript.dll` has a different sha256 (`9cb3ace7916fbe3876970f58870a6635f32ebeb0ab4aecece7a96be31434b2eb`) I had to change both the offset of the PE timestamp and the one of the function inside the DLL, while I wasn't able to figure out what does `stack: 56` refers to (how should be set this parameter?). Below you can see my definition of the hook:

```
   COleScript_Compile:                                                                                                                                                                                            
     module: vbscript
     offsets:
       0x512080e8:
         bitmode: 32
         offset: 0x12af0
         register: r8
         stack: 56
         logging:
        - u script r8
        - u type stk0
```

Despite of this, the hook seems not working yet. Is there some useful documentation about this "special" hooks? I can't find nothing but that article on the web, and I have no idea what is wrong with the above definition.

I'm working with a Windows 7 Professional x64 (SP1) VM and the sample I'm using for tests is a simple "Hello World" VBS script. My version of `vbscript.dll` is 5.8.9200.16521.

(I've tried with `bitmode: 64` too)

Edit:
I checked the steps I followed to reach the above definition on the same `vbscript.dll` version used in the article, and they seems to be correct since I can obtain the same offsets used in the production version of this hook. What am i missing?
